# Vault 설정 파일
# 환경변수나 시스템 프로퍼티로 오버라이드 가능

# Vault 서버 설정
vault.url=http://127.0.0.1:8200

# AppRole 인증 설정
vault.auth.type=approle
vault.approle.role_id=4060cafc-6cda-3bb4-a690-63177f9a5bc6
vault.approle.secret_id=715d4f2c-20ed-6aac-235d-b075b65c9d74

# Token renewal 설정
vault.token.renewal.enabled=true
vault.token.renewal.threshold=0.8

# KV 시크릿 엔진 설정
vault.kv.path=my-vault-app-kv

# Database 시크릿 엔진 설정
vault.database.path=my-vault-app-database
vault.database.dynamic.role=db-demo-dynamic
vault.database.static.role=db-demo-static
